"""
Django settings for namessite project.

Generated by 'django-admin startproject' using Django 2.2.26.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import configparser
import os
from pathlib import Path

from elastictools import docstore

BASE_DIR = Path(__file__).absolute().parent.parent

CONFIG_FILES = [
    '/etc/ddr/namespub.cfg',
    '/etc/ddr/namespub-local.cfg'
]
config = configparser.ConfigParser()
configs_read = config.read(CONFIG_FILES)
if not configs_read:
    raise Exception('No config file!')

SECRET_KEY = config.get('security', 'secret_key')
DEBUG = config.getboolean('debug', 'debug')
ALLOWED_HOSTS = [
    host.strip() for host in config.get('security', 'allowed_hosts').split(',')
]

# Elasticsearch
DOCSTORE_HOST = config.get('database', 'docstore_host')
DOCSTORE_SSL_CERTFILE = config.get('database', 'docstore_ssl_certfile')
DOCSTORE_USERNAME = 'elastic'
DOCSTORE_PASSWORD = config.get('database', 'docstore_password')
_docstore_clusters = config.get('database', 'docstore_clusters')
DOCSTORE_CLUSTER = docstore.cluster(_docstore_clusters, DOCSTORE_HOST)

INSTALLED_APPS = [
    #'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    #
    'bootstrap_pagination',
    'drf_yasg',
    'rest_framework',
    #
    'namespub',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'namespub.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'namessite.wsgi.application'

# https://docs.djangoproject.com/en/2.2/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}
print(DATABASES['default']['NAME'])

# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# https://docs.djangoproject.com/en/2.2/topics/i18n/
LANGUAGE_CODE = 'en-us'
TIME_ZONE='America/Los_Angeles'
USE_I18N = True
USE_L10N = True
USE_TZ = True


# https://docs.djangoproject.com/en/2.2/howto/static-files/
STATIC_ROOT = config.get('assets', 'static_root')
STATIC_URL='/static/'
